### ISSUE TITLE
There isn't border attribute

### ISSUE THREAD

**Issue by ensarkurrt** [wjtje/flutter-skeleton-animation#6]
I try to add border with container but doesn't worked too. How can i add border to skeleton ?

**Comment by wjtje** [comment]
I added support for borders in this pull request.
Hopefully this is what you were looking for.

```dart
Skeleton(
  style: SkeletonStyle.text,
  border: Border.all(width: 2.0),
  height: 14.0,
)
```

<img src="https://i.ibb.co/dkcZ0LM/border.gif"/>
